FROM quay.io/signalfuse/maestro-base:alp-3.4
MAINTAINER Maxime Petazzoni <max@signalfx.com>

ENV JAVA_VERSION=8 JAVA_UPDATE=111 JAVA_BUILD=14 JAVA_HOME=/opt/jdk8 JAVA_JCE=unlimited GLIBC_VERSION=2.23-r3
ENV PATH=$JAVA_HOME/bin:$PATH
ADD ./install_jdk /opt/install_jdk
RUN /opt/install_jdk
