#!/bin/sh

set -e
set -x

mkdir -p /opt
echo "Installing Java JDK ${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD} into ${JAVA_HOME}..."
curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" \
    "http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD}/jdk-${JAVA_VERSION}u${JAVA_UPDATE}-linux-x64.tar.gz" \
  | tar -xzf - -C /opt
ln -s /opt/jdk1.${JAVA_VERSION}.0_${JAVA_UPDATE} ${JAVA_HOME}

if [ "${JAVA_JCE}" = "unlimited" ]; then
   echo "Installing Unlimited JCE policy";
   curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/jce_policy-${JAVA_VERSION}.zip \
        http://download.oracle.com/otn-pub/java/jce/${JAVA_VERSION}/jce_policy-${JAVA_VERSION}.zip;
   cd /tmp
   unzip /tmp/jce_policy-${JAVA_VERSION}.zip;
   cp -v /tmp/UnlimitedJCEPolicyJDK${JAVA_VERSION}/*.jar /opt/jdk${JAVA_VERSION}/jre/lib/security/;
   rm -rf /tmp/UnlimitedJCEPolicyJDK${JAVA_VERSION}/
fi

rm -rf ${JAVA_HOME}/*src.zip \
       ${JAVA_HOME}/lib/missioncontrol \
       ${JAVA_HOME}/lib/visualvm \
       ${JAVA_HOME}/lib/*javafx* \
       ${JAVA_HOME}/jre/bin/javaws \
       ${JAVA_HOME}/jre/bin/jjs \
       ${JAVA_HOME}/jre/bin/keytool \
       ${JAVA_HOME}/jre/bin/orbd \
       ${JAVA_HOME}/jre/bin/pack200 \
       ${JAVA_HOME}/jre/bin/policytool \
       ${JAVA_HOME}/jre/bin/rmid \
       ${JAVA_HOME}/jre/bin/rmiregistry \
       ${JAVA_HOME}/jre/bin/servertool \
       ${JAVA_HOME}/jre/bin/tnameserv \
       ${JAVA_HOME}/jre/bin/unpack200 \
       ${JAVA_HOME}/jre/lib/javaws.jar \
       ${JAVA_HOME}/jre/lib/desktop \
       ${JAVA_HOME}/jre/plugin \
       ${JAVA_HOME}/jre/lib/deploy* \
       ${JAVA_HOME}/jre/lib/plugin.jar \
       ${JAVA_HOME}/jre/lib/*javafx* \
       ${JAVA_HOME}/jre/lib/*jfx* \
       ${JAVA_HOME}/jre/lib/amd64/libdecora_sse.so \
       ${JAVA_HOME}/jre/lib/amd64/libprism_*.so \
       ${JAVA_HOME}/jre/lib/amd64/libfxplugins.so \
       ${JAVA_HOME}/jre/lib/amd64/libglass.so \
       ${JAVA_HOME}/jre/lib/amd64/libgstreamer-lite.so \
       ${JAVA_HOME}/jre/lib/amd64/libjavafx*.so \
       ${JAVA_HOME}/jre/lib/amd64/libjfx*.so \
       ${JAVA_HOME}/jre/lib/ext/jfxrt.jar \
       ${JAVA_HOME}/jre/lib/ext/nashorn.jar \
       ${JAVA_HOME}/jre/lib/oblique-fonts

echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh
echo "jdk-${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD} installed $(date)" >> /root/.built
