#!/bin/sh

set -e
set -x

echo "Install glibc-2.21-r2..."
apk-install libgcc
wget "https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk" \
     "https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-bin-2.21-r2.apk" \
  -P /var/cache/apk
apk-install --allow-untrusted /var/cache/apk/glibc-2.21-r2.apk /var/cache/apk/glibc-bin-2.21-r2.apk
/usr/glibc/usr/bin/ldconfig /lib /usr/glibc/usr/lib

mkdir -p /opt
echo "Installing Java JDK ${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD} into ${JAVA_HOME}..."
curl -jkLH "Cookie: oraclelicense=accept-securebackup-cookie" \
    "http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD}/jdk-${JAVA_VERSION}u${JAVA_UPDATE}-linux-x64.tar.gz" \
  | tar -xzf - -C /opt
ln -s /opt/jdk1.${JAVA_VERSION}.0_${JAVA_UPDATE} ${JAVA_HOME}

rm -rf ${JAVA_HOME}/*src.zip \
       ${JAVA_HOME}/lib/missioncontrol \
       ${JAVA_HOME}/lib/visualvm \
       ${JAVA_HOME}/lib/*javafx* \
       ${JAVA_HOME}/jre/bin/javaws \
       ${JAVA_HOME}/jre/bin/jjs \
       ${JAVA_HOME}/jre/bin/keytool \
       ${JAVA_HOME}/jre/bin/orbd \
       ${JAVA_HOME}/jre/bin/pack200 \
       ${JAVA_HOME}/jre/bin/policytool \
       ${JAVA_HOME}/jre/bin/rmid \
       ${JAVA_HOME}/jre/bin/rmiregistry \
       ${JAVA_HOME}/jre/bin/servertool \
       ${JAVA_HOME}/jre/bin/tnameserv \
       ${JAVA_HOME}/jre/bin/unpack200 \
       ${JAVA_HOME}/jre/lib/javaws.jar \
       ${JAVA_HOME}/jre/lib/desktop \
       ${JAVA_HOME}/jre/plugin \
       ${JAVA_HOME}/jre/lib/deploy* \
       ${JAVA_HOME}/jre/lib/plugin.jar \
       ${JAVA_HOME}/jre/lib/*javafx* \
       ${JAVA_HOME}/jre/lib/*jfx* \
       ${JAVA_HOME}/jre/lib/amd64/libdecora_sse.so \
       ${JAVA_HOME}/jre/lib/amd64/libprism_*.so \
       ${JAVA_HOME}/jre/lib/amd64/libfxplugins.so \
       ${JAVA_HOME}/jre/lib/amd64/libglass.so \
       ${JAVA_HOME}/jre/lib/amd64/libgstreamer-lite.so \
       ${JAVA_HOME}/jre/lib/amd64/libjavafx*.so \
       ${JAVA_HOME}/jre/lib/amd64/libjfx*.so \
       ${JAVA_HOME}/jre/lib/ext/jfxrt.jar \
       ${JAVA_HOME}/jre/lib/ext/nashorn.jar \
       ${JAVA_HOME}/jre/lib/oblique-fonts

echo "hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4" >> /etc/nsswitch.conf
echo "jdk-${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD} installed $(date)" >> /root/.built
