#!/bin/sh

set -e
set -x

echo "Install glibc-${GLIBC_VERSION}..."
apk-install libstdc++
for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION} glibc-i18n-${GLIBC_VERSION}; do
    curl -sSL https://github.com/andyshinn/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk;
done
apk add --allow-untrusted /tmp/*.apk
rm -v /tmp/*.apk
( /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8)
/usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib

apk del glibc-i18n
echo "hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4" >> /etc/nsswitch.conf
